# coding: utf-8

"""
    PRO SHIPPING API

    # Introduction Here you will find requirements for integrating with PRO SHIPPING API.  The documentation specifically covers how the API can be used by business customers to conduct shipping activity with available carriers and provides the technical information to build this integration. The API allows customers to create and manage shipments, produce labels, customs documentation, and collection manifests, retrieve reference data such as carriers and countries, and maintain their own data such as shipping account details.  Pro Shipping API is a fully RESTful service implemented using JSON messaging. You, as the customer are responsible for sending JSON messages and for maintaining the capability of receiving JSON messages in the format described in this specification. Request and response examples for each API service are included in this specification.  # Authentication  The PRO SHIPPING API uses OAuth2 authentication.  To request the authorization token you need to create API credentials (Client ID and Secret) on the system first. If you have not done it already, log into your account and go to API Credentials or follow the link [add a link here with the path to the API Credentials menu]. Use the credentials to retrieve the authorization token.  Note: Make sure you copy the Secret and keep it secure as you won't be able to view it again on the system.  <!-- ReDoc-Inject: <SecurityDefinitions /> -->   # noqa: E501

    OpenAPI spec version: v4.0-RM
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ErrorDetail(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'message': 'str',
        'cause': 'str',
        'error_code': 'str'
    }

    attribute_map = {
        'message': 'Message',
        'cause': 'Cause',
        'error_code': 'ErrorCode'
    }

    def __init__(self, message=None, cause=None, error_code=None):  # noqa: E501
        """ErrorDetail - a model defined in Swagger"""  # noqa: E501
        self._message = None
        self._cause = None
        self._error_code = None
        self.discriminator = None
        if message is not None:
            self.message = message
        if cause is not None:
            self.cause = cause
        if error_code is not None:
            self.error_code = error_code

    @property
    def message(self):
        """Gets the message of this ErrorDetail.  # noqa: E501

        Message <br />The error message, or issue.  # noqa: E501

        :return: The message of this ErrorDetail.  # noqa: E501
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this ErrorDetail.

        Message <br />The error message, or issue.  # noqa: E501

        :param message: The message of this ErrorDetail.  # noqa: E501
        :type: str
        """

        self._message = message

    @property
    def cause(self):
        """Gets the cause of this ErrorDetail.  # noqa: E501

        Cause <br />The cause of the error.  # noqa: E501

        :return: The cause of this ErrorDetail.  # noqa: E501
        :rtype: str
        """
        return self._cause

    @cause.setter
    def cause(self, cause):
        """Sets the cause of this ErrorDetail.

        Cause <br />The cause of the error.  # noqa: E501

        :param cause: The cause of this ErrorDetail.  # noqa: E501
        :type: str
        """

        self._cause = cause

    @property
    def error_code(self):
        """Gets the error_code of this ErrorDetail.  # noqa: E501

        Error Code <br />The error code for this error.<br /><br />**E1000** - System error<br />**E1001** - Required field<br />**E1002** - Invalid field<br />**E1003** - Invalid action<br />**E1004** - Item not found<br />  # noqa: E501

        :return: The error_code of this ErrorDetail.  # noqa: E501
        :rtype: str
        """
        return self._error_code

    @error_code.setter
    def error_code(self, error_code):
        """Sets the error_code of this ErrorDetail.

        Error Code <br />The error code for this error.<br /><br />**E1000** - System error<br />**E1001** - Required field<br />**E1002** - Invalid field<br />**E1003** - Invalid action<br />**E1004** - Item not found<br />  # noqa: E501

        :param error_code: The error_code of this ErrorDetail.  # noqa: E501
        :type: str
        """

        self._error_code = error_code

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ErrorDetail, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ErrorDetail):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
