# coding: utf-8

"""
    Royal Mail API Shipping V2 (REST)

    This API specification details the requirements for integrating with Royal Mail API Shipping V2 (REST). It specifically covers how the Royal Mail API Shipping V2 (REST) can be used by business customers to conduct shipping activity with Royal Mail and provides the technical information to build this integration. This specification must be used with the relevant accompanying specifications for customers wishing to interface their systems with Royal Mail services.  Royal Mail API Shipping V2 (REST) exposes a fully RESTful service that allows account customers to create shipments, produce labels, and produce documentation for all the tasks required to ship domestic items with Royal Mail. Built on industry standards, Royal Mail API Shipping V2 (REST) provides a simple and low cost method for customers to integrate with Royal Mail, and allows them to get shipping quickly. The API offers data streaming and offline barcoding to allow customers greater flexibility when generating their labels.  There are no costs to customers for using the Royal Mail API Shipping V2 (REST) services, however customers’ own development costs must be covered by the customer developing the solution. Royal Mail will not accept any responsibility for these development, implementation and testing costs. Customers should address initial enquiries regarding development of systems for these purposes to their account handler.  This API can be used in conjunction with Royal Mail Pro Shipping, a GUI based shipping platform. For more details on Royal Mail Pro Shipping, including videos on and briefs on updating cancelling a shipment and manifesting click here&#58; www.royalmail.com/pro-shipping-help  # noqa: E501

    OpenAPI spec version: 1.0.21
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class RecipientContact(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'complementary_name': 'str',
        'telephone_number': 'str',
        'electronic_address': 'str'
    }

    attribute_map = {
        'name': 'name',
        'complementary_name': 'complementaryName',
        'telephone_number': 'telephoneNumber',
        'electronic_address': 'electronicAddress'
    }

    def __init__(self, name=None, complementary_name=None, telephone_number=None, electronic_address=None):  # noqa: E501
        """RecipientContact - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._complementary_name = None
        self._telephone_number = None
        self._electronic_address = None
        self.discriminator = None
        self.name = name
        if complementary_name is not None:
            self.complementary_name = complementary_name
        if telephone_number is not None:
            self.telephone_number = telephone_number
        if electronic_address is not None:
            self.electronic_address = electronic_address

    @property
    def name(self):
        """Gets the name of this RecipientContact.  # noqa: E501

        Contact name  # noqa: E501

        :return: The name of this RecipientContact.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this RecipientContact.

        Contact name  # noqa: E501

        :param name: The name of this RecipientContact.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def complementary_name(self):
        """Gets the complementary_name of this RecipientContact.  # noqa: E501

        Business name  # noqa: E501

        :return: The complementary_name of this RecipientContact.  # noqa: E501
        :rtype: str
        """
        return self._complementary_name

    @complementary_name.setter
    def complementary_name(self, complementary_name):
        """Sets the complementary_name of this RecipientContact.

        Business name  # noqa: E501

        :param complementary_name: The complementary_name of this RecipientContact.  # noqa: E501
        :type: str
        """

        self._complementary_name = complementary_name

    @property
    def telephone_number(self):
        """Gets the telephone_number of this RecipientContact.  # noqa: E501

        UK mobile phone number. Required if a SMS service enhancement is selected.  # noqa: E501

        :return: The telephone_number of this RecipientContact.  # noqa: E501
        :rtype: str
        """
        return self._telephone_number

    @telephone_number.setter
    def telephone_number(self, telephone_number):
        """Sets the telephone_number of this RecipientContact.

        UK mobile phone number. Required if a SMS service enhancement is selected.  # noqa: E501

        :param telephone_number: The telephone_number of this RecipientContact.  # noqa: E501
        :type: str
        """

        self._telephone_number = telephone_number

    @property
    def electronic_address(self):
        """Gets the electronic_address of this RecipientContact.  # noqa: E501

        Email address to be used for notifications. Required if Email enhancement is selected  # noqa: E501

        :return: The electronic_address of this RecipientContact.  # noqa: E501
        :rtype: str
        """
        return self._electronic_address

    @electronic_address.setter
    def electronic_address(self, electronic_address):
        """Sets the electronic_address of this RecipientContact.

        Email address to be used for notifications. Required if Email enhancement is selected  # noqa: E501

        :param electronic_address: The electronic_address of this RecipientContact.  # noqa: E501
        :type: str
        """

        self._electronic_address = electronic_address

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(RecipientContact, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RecipientContact):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
