# coding: utf-8

"""
    Royal Mail API Shipping V3 (REST)

    This API specification details the requirements for integrating with **Royal Mail API Shipping V3**.<br><br>It specifically covers how the Royal Mail API Shipping V3 can be used by business customers to conduct shipping activity with Royal Mail and provides the technical information to build this integration. This specification must be used with the relevant accompanying specifications for customers wishing to interface their systems with Royal Mail services.<br><br>Royal Mail API Shipping V3 exposes a fully RESTful service that allows account customers to create shipments, produce labels, and produce documentation for all the tasks required to ship domestic items with Royal Mail.<br><br>Built on industry standards, Royal Mail API Shipping V3 provides a simple and low cost method for customers to integrate with Royal Mail, and allows them to get shipping quickly. The API offers data streaming and offline barcoding to allow customers greater flexibility when generating their labels. There are no costs to customers for using the Royal Mail API Shipping V3 services, however customers’ own development costs must be covered by the customer developing the solution. Royal Mail will not accept any responsibility for these development, implementation and testing costs. Customers should address initial enquiries regarding development of systems for these purposes to their account handler.<br><br>This API can be used in conjunction with Royal Mail Pro Shipping, a GUI based shipping platform. For more details on Royal Mail Pro Shipping, including videos on and briefs on updating/ cancelling a shipment and Manifesting please refer to http://www.royalmail.com/pro-shipping-help.  # noqa: E501

    OpenAPI spec version: 3.0.12
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class ErrorDetail(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'message': 'str',
        'cause': 'str',
        'error_code': 'str',
        'error_id': 'str'
    }

    attribute_map = {
        'message': 'Message',
        'cause': 'Cause',
        'error_code': 'ErrorCode',
        'error_id': 'ErrorId'
    }

    def __init__(self, message=None, cause=None, error_code=None, error_id=None):  # noqa: E501
        """ErrorDetail - a model defined in Swagger"""  # noqa: E501
        self._message = None
        self._cause = None
        self._error_code = None
        self._error_id = None
        self.discriminator = None
        if message is not None:
            self.message = message
        if cause is not None:
            self.cause = cause
        if error_code is not None:
            self.error_code = error_code
        if error_id is not None:
            self.error_id = error_id

    @property
    def message(self):
        """Gets the message of this ErrorDetail.  # noqa: E501

        Message<br />The error message, or issue.  # noqa: E501

        :return: The message of this ErrorDetail.  # noqa: E501
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this ErrorDetail.

        Message<br />The error message, or issue.  # noqa: E501

        :param message: The message of this ErrorDetail.  # noqa: E501
        :type: str
        """

        self._message = message

    @property
    def cause(self):
        """Gets the cause of this ErrorDetail.  # noqa: E501

        Cause<br />The cause of the error.  # noqa: E501

        :return: The cause of this ErrorDetail.  # noqa: E501
        :rtype: str
        """
        return self._cause

    @cause.setter
    def cause(self, cause):
        """Sets the cause of this ErrorDetail.

        Cause<br />The cause of the error.  # noqa: E501

        :param cause: The cause of this ErrorDetail.  # noqa: E501
        :type: str
        """

        self._cause = cause

    @property
    def error_code(self):
        """Gets the error_code of this ErrorDetail.  # noqa: E501

        Error Code<br />The error code for this error.<br /><br />**E1431** - System error<br />**E1432** - Required field<br />**E1433** - Invalid field<br />**E1434** - Invalid action<br />**E1435** - Item not found<br />  # noqa: E501

        :return: The error_code of this ErrorDetail.  # noqa: E501
        :rtype: str
        """
        return self._error_code

    @error_code.setter
    def error_code(self, error_code):
        """Sets the error_code of this ErrorDetail.

        Error Code<br />The error code for this error.<br /><br />**E1431** - System error<br />**E1432** - Required field<br />**E1433** - Invalid field<br />**E1434** - Invalid action<br />**E1435** - Item not found<br />  # noqa: E501

        :param error_code: The error_code of this ErrorDetail.  # noqa: E501
        :type: str
        """

        self._error_code = error_code

    @property
    def error_id(self):
        """Gets the error_id of this ErrorDetail.  # noqa: E501

        Error Log Id<br />The associated Error Log Id if exists.  # noqa: E501

        :return: The error_id of this ErrorDetail.  # noqa: E501
        :rtype: str
        """
        return self._error_id

    @error_id.setter
    def error_id(self, error_id):
        """Sets the error_id of this ErrorDetail.

        Error Log Id<br />The associated Error Log Id if exists.  # noqa: E501

        :param error_id: The error_id of this ErrorDetail.  # noqa: E501
        :type: str
        """

        self._error_id = error_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ErrorDetail, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ErrorDetail):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
