# coding: utf-8

"""
    Royal Mail API Shipping V3 (REST)

    This API specification details the requirements for integrating with **Royal Mail API Shipping V3**.<br><br>It specifically covers how the Royal Mail API Shipping V3 can be used by business customers to conduct shipping activity with Royal Mail and provides the technical information to build this integration. This specification must be used with the relevant accompanying specifications for customers wishing to interface their systems with Royal Mail services.<br><br>Royal Mail API Shipping V3 exposes a fully RESTful service that allows account customers to create shipments, produce labels, and produce documentation for all the tasks required to ship domestic items with Royal Mail.<br><br>Built on industry standards, Royal Mail API Shipping V3 provides a simple and low cost method for customers to integrate with Royal Mail, and allows them to get shipping quickly. The API offers data streaming and offline barcoding to allow customers greater flexibility when generating their labels. There are no costs to customers for using the Royal Mail API Shipping V3 services, however customers’ own development costs must be covered by the customer developing the solution. Royal Mail will not accept any responsibility for these development, implementation and testing costs. Customers should address initial enquiries regarding development of systems for these purposes to their account handler.<br><br>This API can be used in conjunction with Royal Mail Pro Shipping, a GUI based shipping platform. For more details on Royal Mail Pro Shipping, including videos on and briefs on updating/ cancelling a shipment and Manifesting please refer to http://www.royalmail.com/pro-shipping-help.  # noqa: E501

    OpenAPI spec version: 3.0.12
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from rmail_apiv3.api_client import ApiClient


class TokenApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def authenticate_post(self, x_rmg_security_username, x_rmg_security_password, **kwargs):  # noqa: E501
        """Authenticates a User and provides token.  # noqa: E501

        Provides security token.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.authenticate_post(x_rmg_security_username, x_rmg_security_password, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str x_rmg_security_username: User Name (required)
        :param str x_rmg_security_password: Password in plain text (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.authenticate_post_with_http_info(x_rmg_security_username, x_rmg_security_password, **kwargs)  # noqa: E501
        else:
            (data) = self.authenticate_post_with_http_info(x_rmg_security_username, x_rmg_security_password, **kwargs)  # noqa: E501
            return data

    def authenticate_post_with_http_info(self, x_rmg_security_username, x_rmg_security_password, **kwargs):  # noqa: E501
        """Authenticates a User and provides token.  # noqa: E501

        Provides security token.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.authenticate_post_with_http_info(x_rmg_security_username, x_rmg_security_password, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str x_rmg_security_username: User Name (required)
        :param str x_rmg_security_password: Password in plain text (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['x_rmg_security_username', 'x_rmg_security_password']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method authenticate_post" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'x_rmg_security_username' is set
        if ('x_rmg_security_username' not in params or
                params['x_rmg_security_username'] is None):
            raise ValueError("Missing the required parameter `x_rmg_security_username` when calling `authenticate_post`")  # noqa: E501
        # verify the required parameter 'x_rmg_security_password' is set
        if ('x_rmg_security_password' not in params or
                params['x_rmg_security_password'] is None):
            raise ValueError("Missing the required parameter `x_rmg_security_password` when calling `authenticate_post`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}
        if 'x_rmg_security_username' in params:
            header_params['X-RMG-Security-Username'] = params['x_rmg_security_username']  # noqa: E501
        if 'x_rmg_security_password' in params:
            header_params['X-RMG-Security-Password'] = params['x_rmg_security_password']  # noqa: E501

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json', 'application/xml'])  # noqa: E501

        # Authentication setting
        auth_settings = ['clientID', 'clientSecret']  # noqa: E501

        return self.api_client.call_api(
            '/token', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
