# coding: utf-8

"""
    Royal Mail API Shipping V3 (REST)

    This API specification details the requirements for integrating with **Royal Mail API Shipping V3**.<br><br>It specifically covers how the Royal Mail API Shipping V3 can be used by business customers to conduct shipping activity with Royal Mail and provides the technical information to build this integration. This specification must be used with the relevant accompanying specifications for customers wishing to interface their systems with Royal Mail services.<br><br>Royal Mail API Shipping V3 exposes a fully RESTful service that allows account customers to create shipments, produce labels, and produce documentation for all the tasks required to ship domestic items with Royal Mail.<br><br>Built on industry standards, Royal Mail API Shipping V3 provides a simple and low cost method for customers to integrate with Royal Mail, and allows them to get shipping quickly. The API offers data streaming and offline barcoding to allow customers greater flexibility when generating their labels. There are no costs to customers for using the Royal Mail API Shipping V3 services, however customers’ own development costs must be covered by the customer developing the solution. Royal Mail will not accept any responsibility for these development, implementation and testing costs. Customers should address initial enquiries regarding development of systems for these purposes to their account handler.<br><br>This API can be used in conjunction with Royal Mail Pro Shipping, a GUI based shipping platform. For more details on Royal Mail Pro Shipping, including videos on and briefs on updating/ cancelling a shipment and Manifesting please refer to http://www.royalmail.com/pro-shipping-help.  # noqa: E501

    OpenAPI spec version: 3.0.12
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class PrintDocumentRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'document_type': 'str',
        'silent_print_profile': 'str'
    }

    attribute_map = {
        'document_type': 'DocumentType',
        'silent_print_profile': 'SilentPrintProfile'
    }

    def __init__(self, document_type=None, silent_print_profile=None):  # noqa: E501
        """PrintDocumentRequest - a model defined in Swagger"""  # noqa: E501
        self._document_type = None
        self._silent_print_profile = None
        self.discriminator = None
        self.document_type = document_type
        if silent_print_profile is not None:
            self.silent_print_profile = silent_print_profile

    @property
    def document_type(self):
        """Gets the document_type of this PrintDocumentRequest.  # noqa: E501

        Document Type<br />What document you would like printed<br />            <br />**CN23** - Customs Documents PDF 100mm x 150mm<br />**CI** - Commercial Invoice PDF A4 Portrait<br />**P** - Proforma PDF A4 Portrait  # noqa: E501

        :return: The document_type of this PrintDocumentRequest.  # noqa: E501
        :rtype: str
        """
        return self._document_type

    @document_type.setter
    def document_type(self, document_type):
        """Sets the document_type of this PrintDocumentRequest.

        Document Type<br />What document you would like printed<br />            <br />**CN23** - Customs Documents PDF 100mm x 150mm<br />**CI** - Commercial Invoice PDF A4 Portrait<br />**P** - Proforma PDF A4 Portrait  # noqa: E501

        :param document_type: The document_type of this PrintDocumentRequest.  # noqa: E501
        :type: str
        """
        if document_type is None:
            raise ValueError("Invalid value for `document_type`, must not be `None`")  # noqa: E501
        allowed_values = ["CN23", "CI", "P"]  # noqa: E501
        if document_type not in allowed_values:
            raise ValueError(
                "Invalid value for `document_type` ({0}), must be one of {1}"  # noqa: E501
                .format(document_type, allowed_values)
            )

        self._document_type = document_type

    @property
    def silent_print_profile(self):
        """Gets the silent_print_profile of this PrintDocumentRequest.  # noqa: E501

        Silent Print Profile<br />If present, resulting documents will be printed using this profile.  # noqa: E501

        :return: The silent_print_profile of this PrintDocumentRequest.  # noqa: E501
        :rtype: str
        """
        return self._silent_print_profile

    @silent_print_profile.setter
    def silent_print_profile(self, silent_print_profile):
        """Sets the silent_print_profile of this PrintDocumentRequest.

        Silent Print Profile<br />If present, resulting documents will be printed using this profile.  # noqa: E501

        :param silent_print_profile: The silent_print_profile of this PrintDocumentRequest.  # noqa: E501
        :type: str
        """

        self._silent_print_profile = silent_print_profile

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PrintDocumentRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PrintDocumentRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
