# coding: utf-8

"""
    Royal Mail API Shipping V3 (REST)

    This API specification details the requirements for integrating with **Royal Mail API Shipping V3**.<br><br>It specifically covers how the Royal Mail API Shipping V3 can be used by business customers to conduct shipping activity with Royal Mail and provides the technical information to build this integration. This specification must be used with the relevant accompanying specifications for customers wishing to interface their systems with Royal Mail services.<br><br>Royal Mail API Shipping V3 exposes a fully RESTful service that allows account customers to create shipments, produce labels, and produce documentation for all the tasks required to ship domestic items with Royal Mail.<br><br>Built on industry standards, Royal Mail API Shipping V3 provides a simple and low cost method for customers to integrate with Royal Mail, and allows them to get shipping quickly. The API offers data streaming and offline barcoding to allow customers greater flexibility when generating their labels. There are no costs to customers for using the Royal Mail API Shipping V3 services, however customers’ own development costs must be covered by the customer developing the solution. Royal Mail will not accept any responsibility for these development, implementation and testing costs. Customers should address initial enquiries regarding development of systems for these purposes to their account handler.<br><br>This API can be used in conjunction with Royal Mail Pro Shipping, a GUI based shipping platform. For more details on Royal Mail Pro Shipping, including videos on and briefs on updating/ cancelling a shipment and Manifesting please refer to http://www.royalmail.com/pro-shipping-help.  # noqa: E501

    OpenAPI spec version: 3.0.12
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class ServiceAvailabilityFormat(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'service_format': 'str',
        'format_description': 'str',
        'max_weight': 'float'
    }

    attribute_map = {
        'service_format': 'ServiceFormat',
        'format_description': 'FormatDescription',
        'max_weight': 'MaxWeight'
    }

    def __init__(self, service_format=None, format_description=None, max_weight=None):  # noqa: E501
        """ServiceAvailabilityFormat - a model defined in Swagger"""  # noqa: E501
        self._service_format = None
        self._format_description = None
        self._max_weight = None
        self.discriminator = None
        if service_format is not None:
            self.service_format = service_format
        self.format_description = format_description
        self.max_weight = max_weight

    @property
    def service_format(self):
        """Gets the service_format of this ServiceAvailabilityFormat.  # noqa: E501

        Service Format<br />An available service format for this service.<br />If blank, then formats are not applicable for this service.<br />            <br />**L** - Letter<br />**F** - Large Letter<br />**P** - Parcel<br />**S** - Printed Papers<br />**Blank** - Not Applicable  # noqa: E501

        :return: The service_format of this ServiceAvailabilityFormat.  # noqa: E501
        :rtype: str
        """
        return self._service_format

    @service_format.setter
    def service_format(self, service_format):
        """Sets the service_format of this ServiceAvailabilityFormat.

        Service Format<br />An available service format for this service.<br />If blank, then formats are not applicable for this service.<br />            <br />**L** - Letter<br />**F** - Large Letter<br />**P** - Parcel<br />**S** - Printed Papers<br />**Blank** - Not Applicable  # noqa: E501

        :param service_format: The service_format of this ServiceAvailabilityFormat.  # noqa: E501
        :type: str
        """
        allowed_values = ["L", "F", "P", "S"]  # noqa: E501
        if service_format not in allowed_values:
            raise ValueError(
                "Invalid value for `service_format` ({0}), must be one of {1}"  # noqa: E501
                .format(service_format, allowed_values)
            )

        self._service_format = service_format

    @property
    def format_description(self):
        """Gets the format_description of this ServiceAvailabilityFormat.  # noqa: E501

        Format Description<br />A description of the Service Format<br />            <br />Letter<br />Large Letter<br />Parcel<br />International Printed Papaers<br />Not Applicable  # noqa: E501

        :return: The format_description of this ServiceAvailabilityFormat.  # noqa: E501
        :rtype: str
        """
        return self._format_description

    @format_description.setter
    def format_description(self, format_description):
        """Sets the format_description of this ServiceAvailabilityFormat.

        Format Description<br />A description of the Service Format<br />            <br />Letter<br />Large Letter<br />Parcel<br />International Printed Papaers<br />Not Applicable  # noqa: E501

        :param format_description: The format_description of this ServiceAvailabilityFormat.  # noqa: E501
        :type: str
        """
        if format_description is None:
            raise ValueError("Invalid value for `format_description`, must not be `None`")  # noqa: E501

        self._format_description = format_description

    @property
    def max_weight(self):
        """Gets the max_weight of this ServiceAvailabilityFormat.  # noqa: E501

        Maximum Weight<br />The maximum weight allowed for this format (or service if formats not applicable) in specified Unit of Measure.  # noqa: E501

        :return: The max_weight of this ServiceAvailabilityFormat.  # noqa: E501
        :rtype: float
        """
        return self._max_weight

    @max_weight.setter
    def max_weight(self, max_weight):
        """Sets the max_weight of this ServiceAvailabilityFormat.

        Maximum Weight<br />The maximum weight allowed for this format (or service if formats not applicable) in specified Unit of Measure.  # noqa: E501

        :param max_weight: The max_weight of this ServiceAvailabilityFormat.  # noqa: E501
        :type: float
        """
        if max_weight is None:
            raise ValueError("Invalid value for `max_weight`, must not be `None`")  # noqa: E501

        self._max_weight = max_weight

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ServiceAvailabilityFormat, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ServiceAvailabilityFormat):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
